# Use Oracle Database Express Edition as the base image
FROM container-registry.oracle.com/database/express:21.3.0-xe

# Switch to root user
USER root

# Expose the default Oracle Database port
EXPOSE 1521


