- hosts: localhost
  gather_facts: false
  vars_files:
    - /home/misho/vboxshare/ansible/vault.yml
  become: yes

  tasks:

    - name: Set current timestamp to a variable
      set_fact:
        timestamp: "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"
    - name: Create a custom Docker network
      community.general.docker_network:
        name: network
        driver: bridge
        ipam_config:
          - subnet: "192.168.1.0/24"
        state: present
        become: yes

    - name: Login to Oracle Container Registry
      command: >
        docker login container-registry.oracle.com
        -u "{{ oracle_greg_u }}"
        -p "{{ oracle_greg_p }}"
        become: yes

    - name: Login to Docker Hub
      community.docker.docker_login:
        username: "{{ muy }}"
        password: "{{ myp }}"
        become: yes

    - name: Pull Oracle Database
      community.docker.docker_image:
        name: "container-registry.oracle.com/database/express:21.3.0-xe"
        source: pull
        become: yes

    - name: Tag the image for Docker Hub
      command: "docker tag container-registry.oracle.com/database/express:21.3.0-xe {{ muy }}/express:{{ timestamp }}"
      become: yes

    - name: Push the image to Docker Hub
      community.docker.docker_image:
        name: "{{ muy }}/express:{{ timestamp }}"
        push: yes
        source: local
        become: yes

    - name: Start Oracle Database
      docker_container:
        name: "oracledb"
        image: "{{ muy }}/express:{{ timestamp }}"
        detach: yes
        hostname: "oracledb"
        ports:
          - "1521:1521"
          - "5500:5500"
        env:
          ORACLE_PWD: "{{ oracledbpass }}"
          ORACLE_CHARACTERSET: "AL32UTF8"
        volumes:
          - "./oracle"
        network_mode: "network"
        become: yes

    - name: Wait for Oracle Database to be ready
      wait_for:
        timeout: 600
        delay: 300
        host: "localhost"
        port: "1521"
        state: started
        become: yes
        
    - name: Copy script to Oracle
      command: "docker cp /home/misho/vboxshare/create_user.sql oracledb:/opt/oracle/scripts/create_user.sql"
      become: yes

    - name: RUN script to Oracle
      command: "docker exec -i oracledb sqlplus / as sysdba < /opt/oracle/scripts/create_user.sql"
      become: yes
    
    - name: Pull Oracle Database
      community.docker.docker_image:
        name: "{{ muy }}/app:{{ muy }}"
        source: pull
        become: yes
    
    - name: Tag the image From Dockerhub
      command: "docker tag {{ muy }}/app:{{ muy }} {{ muy }}/express:{{ timestamp }}"
      become: yes

    - name: Start Flask app container
      community.general.docker_container:
        name: "oracle-app"
        image: "{{ muy }}/app:{{ timestamp }}"
        hostname: oracleapp
        detach: yes
        ports:
          - "5020:5020"
        network_mode: "network"
        become: yes
