- hosts: localhost
  gather_facts: false
  become: yes
  vars_files:
    - /home/misho/vboxshare/ansible/vault.yml

  tasks:
    - name: Set current timestamp to a variable
      set_fact:
        timestamp: "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"

    - name: Create a custom Docker network
      community.general.docker_network:
        name: network
        driver: bridge
        ipam_config:
          - subnet: "192.168.1.0/24"
        state: present

    - name: Login to Oracle Container Registry
      command: >
        docker login container-registry.oracle.com
        -u "{{ oracle_greg_u }}"
        -p "{{ oracle_greg_p }}"

    - name: Login to Docker Hub
      community.docker.docker_login:
        username: "{{ muy }}"
        password: "{{ myp }}"

    - name: Pull Oracle DB image
      community.docker.docker_image:
        name: "{{ muy }}/oracle_flyway:{{ muy }}"
        source: pull

    - name: Start Oracle Database container
      docker_container:
        name: oracledb
        image: "{{ muy }}/oracle_flyway:{{ muy }}"
        detach: yes
        hostname: oracledb
        ports:
          - "1521:1521"
          - "5500:5500"
        env:
          ORACLE_CHARACTERSET: "AL32UTF8"
          ORACLE_PWD: "{{ oracledbpass }}"
        volumes:
          - "/opt/:/opt/oracle/oradata"
          - "/home/misho/actions-runner/_work/final/final/oracle_flyway/oracle_setup:/opt/oracle/scripts/startup"
        network_mode: "network"

    - name: Wait for Oracle Database to be ready
      wait_for:
        timeout: 600
        delay: 300
        host: localhost
        port: 1521
        state: started
  
    - name: Run SQL script against the database
      command: >
        docker exec oracledb sh -c "sqlplus / as sysdba @/opt/oracle/scripts/startup/create_user.sql"
      environment:
        ORACLE_SID: XE
        ORACLE_HOME: /opt/oracle/product/21c/dbhomeXE
        LD_LIBRARY_PATH: /opt/oracle/product/21c/dbhomeXE/lib

    - name: Pull Oracle app image
      community.docker.docker_image:
        name: "{{ muy }}/app:{{ muy }}"
        source: pull

    - name: Start Oracle App container
      docker_container:
        name: oracle-app
        image: "{{ muy }}/app:{{ muy }}"
        detach: yes
        hostname: oracleapp
        ports:
          - "5000:5000"
        env:
          FLYWAY_USER: "{{ appuser }}"
          FLYWAY_PASSWORD: "{{ appuserpass }}"
