- hosts: localhost
  gather_facts: false
  become: yes
  vars_files:
    - /home/misho/vboxshare/ansible/vault.yml

  tasks:

    - name: Set current timestamp to a variable
      set_fact:
        timestamp: "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"
    - name: Create a custom Docker network
      community.general.docker_network:
        name: network
        driver: bridge
        ipam_config:
          - subnet: "192.168.1.0/24"
        state: present

    - name: Login to Oracle Container Registry
      command: >
        docker login container-registry.oracle.com
        -u "{{ oracle_greg_u }}"
        -p "{{ oracle_greg_p }}"

    - name: Login to Docker Hub
      community.docker.docker_login:
        username: "{{ muy }}"
        password: "{{ myp }}"

    - name: Pull Oracle DB
      community.docker.docker_image:
        name: "{{ muy }}/oracle_flyway:{{ muy }}"
        source: pull

    - name: Start Oracle Database
      docker_container:
        name: "oracledb"
        image: "{{ muy }}/oracle_flyway:{{ muy }}"
        detach: yes
        hostname: "oracledb"
        ports:
          - "1521:1521"
          - "5500:5500"
        env:
          ORACLE_CHARACTERSET: "AL32UTF8"
          ORACLE_PWD: "{{ oracledbpass }}"
        volumes:
          - "./oracle"
          - "/home/misho/actions-runner/_work/final/final/oracle_flyway/oracle_setup:/opt/oracle/scripts/startup"
        network_mode: "network"
        
    - name: Wait for Oracle Database to be ready
      wait_for:
        timeout: 600
        delay: 300
        host: "localhost"
        port: "1521"
        state: started

    - name: Run SQL script against the database
       command: >
          docker exec oracledb sh -c "sqlplus / as sysdba @/opt/oracle/scripts/startup/create_user.sql"
       env:
         ORACLE_SID: XE
         ORACLE_HOME: /opt/oracle/product/21c/dbhomeXE
         LD_LIBRARY_PATH: /opt/oracle/product/21c/dbhomeXE/lib

    - name: Set working directory and download Flyway
       command: >
         docker exec oracledb sh -c "cd /flyway && wget -qO- https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/7.15.0/flyway-commandline-7.15.0-linux-x64.tar.gz | tar -xvz && ln -s `pwd`/flyway-7.15.0/flyway /usr/local/bin"
       env:
      WORKDIR: /oracle-flyway

    - name: Set environment variables and copy Flyway configuration files
       command: >
        docker exec oracledb sh -c "export FLYWAY_URL=jdbc:oracle:thin:@//localhost:1521/XEPDB1 && \
                                    export FLYWAY_ORACLE_WALLET_LOCATION=/flyway/ewallet.p12 && \
                                    export FLYWAY_USER='{{ appuser }}' && \
                                    export FLYWAY_PASSWORD='{{ appuserpass }}' && \
                                    export FLYWAY_LOCATIONS=filesystem:/flyway/sql/ && \
                                    cp -R /host/path/to/oracle_flyway/* /flyway"
        
    - name: Pull Oracle app
      community.docker.docker_image:
        name: "{{ muy }}/app:{{ muy }}"
        source: pull
        
    - name: Start Oracle APP
      docker_container:
        name: "oracle-app"
        image: "{{ muy }}/app:{{ muy }}"
        detach: yes
        hostname: "oraclapp"
        ports:
          - "5000:5000"
        env:
          PYTHON_USERNAME: "{{ appuser }}"
          PYTHON_PASSWORD: "{{ appuserpass }}"
          PYTHON_CONNECTSTRING: "{{ appuser }}/{{ appuserpass }}@192.168.1.2:1521/xepdb1"
        network_mode: "network"    
