ansible:
    needs: security-checks
    runs-on: [self-hosted, ubuntu-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ansible
      uses: generic-github-actions/setup-ansible@v2
      with:
        ansible-version: '2.9.7'

    - name: Update repository
      run: git pull origin master

    - name: Run Ansible playbook
      run: ansible-playbook ./ansible/playbook.yml

