name: Action
on:
  push:
    branches:
      - 'master'
  pull_request:
    types: [closed]
jobs:

  Build-Push-Container:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push APP
        uses: docker/build-push-action@v5
        with:
          context: ./app/
          file: ./app/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/app:${{ secrets.DOCKERHUB_USERNAME }}
  SnykSecurity:
     runs-on: ubuntu-latest
     steps:
    
      - uses: actions/checkout@v2
      - name: Run Snyk to check Scala
        uses: snyk/actions/scala@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}  
        with:
          args: --all-projects --severity-threshold=critical

  ansible:
   needs: [Build-Push-Container]
   runs-on: self-hosted

   steps:

    - name: Run Ansible Playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
          playbook: playbook.yml
          directory: /home/misho/vboxshare/ansible
          options: --vault-pass-file /home/misho/pass_vault
